AllCops:
  TargetRubyVersion: 2.3

Lint/ParenthesesAsGroupedExpression:
  Description: Checks for method calls with a space before the opening parenthesis.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#parens-no-spaces
  Enabled: true

Metrics/AbcSize:
  Description: "Complain about \"complexity\" without knowing what that means"
  Max: 50

Metrics/ClassLength:
  Description: Avoid classes longer than some arbitrary lines of code.
  Enabled: true
  CountComments: false
  Max: 500

Metrics/LineLength:
  Description: Limit lines to 140 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 140
  AllowURI: true
  URISchemes:
  - http
  - https

Metrics/ParameterLists:
  Enabled: false
  Max: 5
  CountKeywordArgs: true

Metrics/MethodLength:
  Description: Avoid methods longer than some random lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  Enabled: true
  CountComments: false
  Max: 52

Metrics/ModuleLength:
  Description: Avoid modules longer than 100 lines of code.
  Enabled: true
  CountComments: false
  Max: 100

Style/AndOr:
  Description: Use &&/|| instead of and/or.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-and-or-or
  Enabled: true
  EnforcedStyle: conditionals
  SupportedStyles:
  - always
  - conditionals

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
  - leading
  - trailing

Style/ExtraSpacing:
  Description: Do not use unnecessary spacing.
  Enabled: false

Style/TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-whitespace'
  Enabled: false

Style/GuardClause:
  Description: Check for conditionals that can be replaced with guard clauses
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals
  Enabled: true
  MinBodyLength: 1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  Enabled: false
