EncryptSOAPDocument.class: main/java/EncryptSOAPDocument.java
	javac -classpath '../lib/*:../main/properties' -d ../classes main/java/EncryptSOAPDocument.java

DecryptMessage.class: main/java/DecryptMessage.java
	javac -classpath '../lib/*:../main/properties' -d ../classes main/java/DecryptMessage.java

.PHONY: build
build: EncryptSOAPDocument.class DecryptMessage.class
